services:
  db:
    image: postgres:15
    container_name: go_postgres
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: gofiber_app
    depends_on:
      - db
    ports:
      - "${SERVER_PORT}:8000"
    volumes:
      - .:/app
    command: air
    env_file:
      - .env

volumes:
  pgdata:
